Repository code-is-evenly-cooked/even-zaro-back, pull requests merged in 2025-06, with the labels that each got.

#105 fix: 댓글 리스트 조회 desc, asc 변동 안되는 버그 수정 - repository 메서드 문제
  src/main/java/com/even/zaro/repository/CommentRepository.java
  src/main/java/com/even/zaro/service/CommentService.java
Labels: 🐛bug

#102 Feat/update profile image 프로필 이미지 변경 API
  src/main/java/com/even/zaro/controller/UserController.java
  src/main/java/com/even/zaro/dto/user/UpdateProfileImageRequestDto.java
  src/main/java/com/even/zaro/dto/user/UpdateProfileImageResponseDto.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/service/UserService.java
  src/test/java/com/even/zaro/service/UserServiceTest.java
Labels: ✨feature

#110 fix: 젠킨스 - 무중단, 자동 배포 스크립트
  Jenkinsfile
Labels: 🔧configuration

#109 Ref/sse notification : 알림 응답 DTO 확장, Notification 엔티티에 컬럼추가
  src/main/java/com/even/zaro/dto/notification/NotificationDto.java
  src/main/java/com/even/zaro/entity/Notification.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/jwt/JwtAuthFilter.java
  src/main/java/com/even/zaro/jwt/JwtUtil.java
  src/main/java/com/even/zaro/listener/CommentListener.java
  src/main/java/com/even/zaro/listener/FollowListener.java
  src/main/java/com/even/zaro/listener/PostLikeListener.java
  src/main/java/com/even/zaro/service/NotificationService.java
Labels: ♻️refactored

#108 Feat/rank : 실시간 인기 게시글 API 구현
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/PostController.java
  src/main/java/com/even/zaro/dto/post/PostRankResponseDto.java
  src/main/java/com/even/zaro/entity/Post.java
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/service/CommentService.java
  src/main/java/com/even/zaro/service/PostLikeService.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: ✨feature

#113 Fix/code reviewed UserService 책임분리
  src/main/java/com/even/zaro/service/UserService.java
  src/test/java/com/even/zaro/service/UserServiceTest.java
Labels: ♻️refactored

#119 Ref/map 지도 API 장소 테이블에 category 필드 추가
  src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
  src/main/java/com/even/zaro/dto/map/MarkerInfoResponse.java
  src/main/java/com/even/zaro/dto/map/PlaceResponse.java
  src/main/java/com/even/zaro/entity/Place.java
  src/main/java/com/even/zaro/service/FavoriteService.java
  src/main/java/com/even/zaro/service/MapService.java
Labels: ♻️refactored

#120 Ref/feedback 그룹, 즐겨찾기, 지도 API 멘토링 피드백 반영
  build.gradle
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/dto/map/PlaceResponse.java
  src/main/java/com/even/zaro/entity/Favorite.java
  src/main/java/com/even/zaro/entity/FavoriteGroup.java
  src/main/java/com/even/zaro/mapper/FavoriteMapper.java
  src/main/java/com/even/zaro/mapper/GroupMapper.java
  src/main/java/com/even/zaro/mapper/MapMapper.java
  src/main/java/com/even/zaro/repository/FavoriteGroupRepository.java
  src/main/java/com/even/zaro/repository/PlaceRepository.java
  src/main/java/com/even/zaro/service/FavoriteService.java
  src/main/java/com/even/zaro/service/GroupService.java
  src/main/java/com/even/zaro/service/MapService.java
Labels: ♻️refactored

#125 Ref/post : 멘토링 피드백 적용
  src/main/java/com/even/zaro/dto/post/ReportRequestDTO.java
  src/main/java/com/even/zaro/entity/Post.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/mapper/PostMapper.java
  src/main/java/com/even/zaro/service/CommentReportService.java
  src/main/java/com/even/zaro/service/PostLikeService.java
  src/main/java/com/even/zaro/service/PostReportService.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: ♻️refactored

#130 Ref/sse notification : 알림생성&전송 event 기반 설계로 refactor, 알림 목록 조회 로직 bug 수정, DTO builder 메서드 분리
  src/main/java/com/even/zaro/event/CommentCreatedEvent.java
  src/main/java/com/even/zaro/event/FollowCreatedEvent.java
  src/main/java/com/even/zaro/event/PostLikeCreatedEvent.java
  src/main/java/com/even/zaro/global/util/NotificationMapper.java
  src/main/java/com/even/zaro/listener/CommentListener.java
  src/main/java/com/even/zaro/listener/FollowListener.java
  src/main/java/com/even/zaro/listener/NotificationListener.java
  src/main/java/com/even/zaro/listener/PostLikeListener.java
  src/main/java/com/even/zaro/service/NotificationService.java
  src/main/java/com/even/zaro/service/NotificationSseService.java
Labels: 🐛bug, ♻️refactored

#132 Fix/oauth 카카오 로그인 버그 수정
  src/main/java/com/even/zaro/dto/auth/KakaoUserInfoDto.java
  src/main/java/com/even/zaro/entity/Gender.java
Labels: 🐛bug

#133 Fix/timezone 타임존 문제로 LocalDateTime 타입 수정
  src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
  src/main/java/com/even/zaro/dto/post/PostDetailResponse.java
  src/main/java/com/even/zaro/dto/post/PostPreviewDto.java
  src/main/java/com/even/zaro/dto/post/PostSearchDto.java
  src/main/java/com/even/zaro/dto/user/UpdateNicknameResponseDto.java
  src/main/java/com/even/zaro/dto/user/UserInfoResponseDto.java
  src/main/java/com/even/zaro/elasticsearch/document/PostEsDocument.java
  src/main/java/com/even/zaro/mapper/PostMapper.java
  src/main/java/com/even/zaro/service/CommentService.java
  src/main/java/com/even/zaro/service/PostEsSearchService.java
  src/main/java/com/even/zaro/service/UserService.java
  src/main/resources/application.yaml
Labels: 🐛bug

#141 Fix/jenkinsfile 젠킨스 파이프라인 수정
  Jenkinsfile
Labels: 🐛bug

#143 feat: 실시간 인기 게시글 기간 제한 추가
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: ✨feature

#136 Ref/group-favorite 그룹, 즐겨찾기 리팩토링(필드 추가, 필터링, 즐겨찾기 상태 조회API 구현)
  src/main/java/com/even/zaro/controller/FavoriteController.java
  src/main/java/com/even/zaro/dto/group/GroupResponse.java
  src/main/java/com/even/zaro/entity/Favorite.java
  src/main/java/com/even/zaro/entity/FavoriteGroup.java
  src/main/java/com/even/zaro/mapper/GroupMapper.java
  src/main/java/com/even/zaro/repository/FavoriteGroupRepository.java
  src/main/java/com/even/zaro/repository/FavoriteRepository.java
  src/main/java/com/even/zaro/service/FavoriteService.java
  src/main/java/com/even/zaro/service/GroupService.java
Labels: ♻️refactored

#144 Feat/dormant user 휴면계정 처리
  src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
  src/main/java/com/even/zaro/repository/UserRepository.java
  src/main/java/com/even/zaro/service/AuthService.java
  src/test/java/com/even/zaro/integration/UserSchedulerIntegrationTest.java
  src/test/java/com/even/zaro/service/UserServiceTest.java
Labels: ✨feature

#147 Fix/signout token 로그아웃 API 수정
  src/main/java/com/even/zaro/controller/AuthController.java
Labels: 🐛bug

#149 Fix/post 게시글 관련 버그 수정
  src/main/java/com/even/zaro/mapper/PostMapper.java
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: 🐛bug

#150 Test/notification sse : NotificationMapper, NotificationSseService 단위테스트 구현
  src/test/java/com/even/zaro/unit/service/NotificationSseServiceTest.java
  src/test/java/com/even/zaro/unit/util/NotificationMapperTest.java
Labels: ✅test

#156 feat : 모든 장소 조회 api
  src/main/java/com/even/zaro/controller/MapController.java
  src/main/java/com/even/zaro/service/MapService.java
Labels: ✨feature

#164 ref: 공통 로직 수정
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: ✨feature

#165 feat : 인근 장소 조회 시 내림차순 정렬
  src/main/java/com/even/zaro/service/MapService.java
Labels: ♻️refactored

#167 Fix/sse notification : sse 인증을 header사용으로 ref -> 불필요 설정 롤백, 연결유지용 ping 전송 코드 추가
  src/main/java/com/even/zaro/controller/AuthController.java
  src/main/java/com/even/zaro/global/jwt/JwtAuthFilter.java
  src/main/java/com/even/zaro/service/NotificationSseService.java
Labels: ✨feature, ♻️refactored

#163 Fix/ex log 로그 추가 및 정리
  build.gradle
  src/main/java/com/even/zaro/global/jwt/JwtAuthFilter.java
  src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
  src/main/resources/application.yaml
Labels: 🐛bug, 🔧configuration

#172 ref : 인근 장소 조회 API 예외 처리 방법 수정
  src/main/java/com/even/zaro/controller/MapController.java
  src/main/java/com/even/zaro/service/MapService.java
Labels: ♻️refactored

#175 fix/ping : Vercel, EC2 앞단 Nginx에서 버퍼링 비활성화
  src/main/java/com/even/zaro/controller/NotificationController.java
Labels: 🐛bug

#174 Ref/comment 댓글 부분 리팩토링(Mapper 적용, totalComments 응답 변경)
  src/main/java/com/even/zaro/controller/CommentController.java
  src/main/java/com/even/zaro/dto/comment/CommentPageResponse.java
  src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/mapper/CommentMapper.java
  src/main/java/com/even/zaro/repository/CommentRepository.java
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/service/CommentReportService.java
  src/main/java/com/even/zaro/service/CommentService.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: ✨feature, ♻️refactored

#176 fix : kakoPlaceId 응답 객체 추가
  src/main/java/com/even/zaro/dto/map/PlaceResponse.java
  src/main/java/com/even/zaro/service/MapService.java
Labels: ♻️refactored

#178 Fix/user 회원 정책 수정 및 리팩토링
  src/main/java/com/even/zaro/controller/CommentController.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
  src/main/java/com/even/zaro/mapper/CommentMapper.java
  src/main/java/com/even/zaro/mapper/PostMapper.java
  src/main/java/com/even/zaro/repository/UserRepository.java
  src/main/java/com/even/zaro/service/CommentReportService.java
  src/main/java/com/even/zaro/service/PostLikeService.java
  src/main/java/com/even/zaro/service/PostReportService.java
  src/main/java/com/even/zaro/service/PostService.java
  src/main/java/com/even/zaro/service/ProfileService.java
  src/main/java/com/even/zaro/service/UserService.java
  src/test/java/com/even/zaro/integration/user/UserSchedulerIntegrationTest.java
  src/test/java/com/even/zaro/unit/service/UserServiceTest.java
Labels: 🐛bug, ♻️refactored

#182 Ref : 팔로우 기능에서 탈퇴한 사용자는 조회하지 않도록 설정 , [sse] emitter 제거하는 시간을 heartbeatTimeout시간과 맞춤
  src/main/java/com/even/zaro/service/NotificationSseService.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: ♻️refactored

#180 Ref/enum converter enum <-> string converter 적용
  src/main/java/com/even/zaro/controller/UserController.java
  src/main/java/com/even/zaro/dto/user/UpdateProfileRequestDto.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/converter/GenderConverter.java
  src/main/java/com/even/zaro/global/converter/MbtiConverter.java
  src/main/java/com/even/zaro/global/converter/ProviderConverter.java
  src/main/java/com/even/zaro/global/converter/StatusConverter.java
  src/main/java/com/even/zaro/global/validator/EnumValidator.java
  src/main/java/com/even/zaro/global/validator/annotation/ValidEnum.java
  src/main/java/com/even/zaro/service/UserService.java
  src/test/java/com/even/zaro/global/converter/EnumConversionPerformanceTest.java
  src/test/java/com/even/zaro/integration/profile/ProfileIntegrationTest.java
Labels: ♻️refactored

#186 Feat/post test 게시글 관련 테스트 코드 작성 및 특정 문자 제거 추가
  src/main/java/com/even/zaro/dto/post/PostCreateRequest.java
  src/main/java/com/even/zaro/dto/post/PostUpdateRequest.java
  src/main/java/com/even/zaro/service/ProfileService.java
  src/test/java/com/even/zaro/unit/service/PostReportTest.java
  src/test/java/com/even/zaro/unit/service/PostServiceTest.java
Labels: ✨feature, ✅test

#187 ref : 그룹 추가시 응답 객체에 그룹 정보 추가 (프론트 요청사항)
  src/main/java/com/even/zaro/controller/GroupController.java
  src/main/java/com/even/zaro/service/GroupService.java
Labels: ♻️refactored

#188 feat: DTO에 카테고리 추가
  src/main/java/com/even/zaro/dto/post/PostRankResponseDto.java
Labels: ✨feature

#191 ref : 인근 장소 조회 API 인증 헤더 제거
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/MapController.java
  src/main/java/com/even/zaro/global/jwt/JwtUtil.java
Labels: 🐛bug

#190 setting/ngrinder : ngrinder local 파일 추가
  docker-compose.ngrinder.local.yml
Labels: ✅test

#193 fix: enum converter 사용으로 코드 변경
  src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
  src/main/java/com/even/zaro/repository/UserRepository.java
Labels: 🐛bug
