Repository code-is-evenly-cooked/even-zaro-back, pull requests merged in 2025-05, with the labels that each got.

#4 [infra] 도커, 도커 컴포즈 셋업
  .env.dev.example
  .env.example
  .env.local.example
  .env.prod.example
  .gitignore
  Dockerfile
  docker-compose.dev.yml
  docker-compose.prod.yml
  src/main/java/com/even/zaro/FinalApplication.java
  src/main/java/com/even/zaro/config/CorsConfig.java
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/ApiTestController.java
  src/main/java/com/even/zaro/dto/ExDTO.java
  src/main/java/com/even/zaro/global/ApiResponse.java
  src/main/java/com/even/zaro/global/exception/GlobalExceptionHandler.java
  src/main/java/com/even/zaro/global/exception/exampleEx/ExampleException.java
  src/main/java/com/even/zaro/global/exception/userEx/UserException.java
  src/main/java/com/even/zaro/healthcheck/HealthCheckController.java
  src/main/java/com/even/zaro/healthcheck/MockEntity.java
  src/main/java/com/even/zaro/healthcheck/MockRepository.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/test/java/com/even/zaro/FinalApplicationTests.java
Labels: 🔧configuration

#6 Config/api-response API 응답 객체 변경
  src/main/java/com/even/zaro/controller/ApiTestController.java
  src/main/java/com/even/zaro/global/ApiResponse.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/exception/GlobalExceptionHandler.java
  src/main/java/com/even/zaro/healthcheck/HealthCheckController.java
Labels: 🔧configuration

#8 Ref/errorcode 커스텀 예외처리 리팩토링
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/ApiTestController.java
  src/main/java/com/even/zaro/global/ApiResponse.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/exception/CustomException.java
  src/main/java/com/even/zaro/global/exception/GlobalExceptionHandler.java
  src/main/java/com/even/zaro/global/exception/exampleEx/ExampleException.java
  src/main/java/com/even/zaro/global/exception/map/MapException.java
  src/main/java/com/even/zaro/global/exception/post/PostException.java
  src/main/java/com/even/zaro/global/exception/profile/ProfileException.java
  src/main/java/com/even/zaro/global/exception/user/UserException.java
  src/main/java/com/even/zaro/global/exception/userEx/UserException.java
  src/main/java/com/even/zaro/healthcheck/HealthCheckController.java
  src/main/java/com/even/zaro/healthcheck/MockEntity.java
Labels: ♻️refactored

#7 Feature/favorite 즐겨찾기 그룹 CRUD API
  src/main/java/com/even/zaro/config/DataInit.java
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/dto/profileDto/GroupCreateRequest.java
  src/main/java/com/even/zaro/dto/profileDto/GroupEditRequest.java
  src/main/java/com/even/zaro/dto/profileDto/GroupResponse.java
  src/main/java/com/even/zaro/entity/Favorite.java
  src/main/java/com/even/zaro/entity/FavoriteGroup.java
  src/main/java/com/even/zaro/entity/Place.java
  src/main/java/com/even/zaro/entity/Status.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/ApiResponse.java
  src/main/java/com/even/zaro/global/exception/GlobalExceptionHandler.java
  src/main/java/com/even/zaro/global/exception/favoriteGroupEx/FavoriteGroupException.java
  src/main/java/com/even/zaro/repository/FavoriteGroupRepository.java
  src/main/java/com/even/zaro/repository/FavoriteRepository.java
  src/main/java/com/even/zaro/repository/PlaceRepository.java
  src/main/java/com/even/zaro/repository/UserRepository.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: ✨feature

#9 Feat/profile 유저프로필 기본정보, 작성한 게시글, 좋아요 한 게시글 조회 CRUD API
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/dto/FollowerFollowingListDto.java
  src/main/java/com/even/zaro/dto/UserPostDto.java
  src/main/java/com/even/zaro/dto/UserProfileDto.java
  src/main/java/com/even/zaro/entity/Post.java
  src/main/java/com/even/zaro/entity/PostLike.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/repository/PostLikeRepository.java
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/repository/UserRepository.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: ✨feature

#10 Refactor : 예외 던지는 방식 변경
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: 🐛bug

#11 Fix/import AllArgs 어노테이션 import문 누락 수정, 불필요한 주석 제거, DataInit.java 삭제
  src/main/java/com/even/zaro/config/DataInit.java
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/healthcheck/HealthCheckController.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: 🐛bug

#12 Hotfix/server swagger cors 에러, https 인식 불가 문제
  .env.dev.example
  .env.local.example
  .env.prod.example
  src/main/java/com/even/zaro/config/CorsConfig.java
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/resources/application.yaml
Labels: 🐛bug

#14 Feat/favorite api 즐겨찾기 그룹의 장소 CRUD API 기능 구현
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
  src/main/java/com/even/zaro/dto/favorite/FavoriteAddResponse.java
  src/main/java/com/even/zaro/dto/favorite/FavoriteEditRequest.java
  src/main/java/com/even/zaro/dto/favorite/FavoriteResponse.java
  src/main/java/com/even/zaro/dto/profile/GroupCreateRequest.java
  src/main/java/com/even/zaro/dto/profile/GroupEditRequest.java
  src/main/java/com/even/zaro/dto/profile/GroupResponse.java
  src/main/java/com/even/zaro/dto/profileDto/GroupEditRequest.java
  src/main/java/com/even/zaro/entity/Favorite.java
  src/main/java/com/even/zaro/entity/FavoriteGroup.java
  src/main/java/com/even/zaro/entity/Post.java
  src/main/java/com/even/zaro/entity/PostLike.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/exception/GlobalExceptionHandler.java
  src/main/java/com/even/zaro/global/exception/favoriteGroupEx/FavoriteGroupException.java
  src/main/java/com/even/zaro/repository/FavoriteRepository.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: ✨feature

#17 Ref/favorite auth Profile API에서 Group,Favorite API 분리, 토큰 인증 처리 추가
  src/main/java/com/even/zaro/controller/FavoriteController.java
  src/main/java/com/even/zaro/controller/GroupController.java
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
  src/main/java/com/even/zaro/dto/profile/GroupCreateRequest.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/exception/favorite/FavoriteException.java
  src/main/java/com/even/zaro/global/exception/group/GroupException.java
  src/main/java/com/even/zaro/service/FavoriteService.java
  src/main/java/com/even/zaro/service/GroupService.java
  src/main/java/com/even/zaro/service/ProfileService.java
  src/main/resources/application.yaml
Labels: ♻️refactored

#20 Feat/image presigned s3 버킷 이미지 업로드 url 출력 API, 이미지 제거 API
  .env.prod.example
  build.gradle
  src/main/java/com/even/zaro/config/S3Config.java
  src/main/java/com/even/zaro/controller/S3Controller.java
  src/main/java/com/even/zaro/dto/PresignedUrlResponse.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/service/S3Service.java
  src/main/resources/application.yaml
Labels: ✨feature

#19 Feat/auth refresh emailveri 로그인 연장, 이메일 인증 API
  .env.dev.example
  .env.local.example
  .env.prod.example
  build.gradle
  src/main/java/com/even/zaro/config/RedisConfig.java
  src/main/java/com/even/zaro/config/SwaggerConfig.java
  src/main/java/com/even/zaro/controller/AuthController.java
  src/main/java/com/even/zaro/dto/auth/RefreshResponseDto.java
  src/main/java/com/even/zaro/dto/auth/ResendEmailRequestDto.java
  src/main/java/com/even/zaro/dto/auth/SignInResponseDto.java
  src/main/java/com/even/zaro/entity/EmailToken.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/exception/user/UserException.java
  src/main/java/com/even/zaro/jwt/JwtAuthFilter.java
  src/main/java/com/even/zaro/jwt/JwtUtil.java
  src/main/java/com/even/zaro/repository/EmailTokenRepository.java
  src/main/java/com/even/zaro/service/AuthService.java
  src/main/java/com/even/zaro/service/EmailService.java
  src/main/java/com/even/zaro/service/EmailVerifyService.java
  src/main/resources/application.yaml
Labels: ✨feature

#22 Hotfix/presigned-url post 이미지 업로드 시 postId 생성 전 이미지 업로드로 postId 삭제
  src/main/java/com/even/zaro/controller/S3Controller.java
  src/main/java/com/even/zaro/service/S3Service.java
Labels: 🐛bug

#18 Feat/profile 유저가 쓴 댓글 조회 API, 팔로우/팔로잉 관련 CRUD API, 커스텀예외처리 추가, Swagger 문서화 추가
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/dto/FollowerFollowingListDto.java
  src/main/java/com/even/zaro/dto/UserPostDto.java
  src/main/java/com/even/zaro/dto/UserProfileDto.java
  src/main/java/com/even/zaro/dto/profile/FollowerFollowingListDto.java
  src/main/java/com/even/zaro/dto/profile/UserCommentDto.java
  src/main/java/com/even/zaro/dto/profile/UserPostDto.java
  src/main/java/com/even/zaro/dto/profile/UserProfileDto.java
  src/main/java/com/even/zaro/entity/Comment.java
  src/main/java/com/even/zaro/entity/Follow.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/exception/comment/CommentException.java
  src/main/java/com/even/zaro/repository/CommentRepository.java
  src/main/java/com/even/zaro/repository/FollowRepository.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: ✨feature

#24 profile/fix : conflix 해결 시 import 잘못 설정된 부분 수정, 불필요 import 삭제
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: 🐛bug

#25 Bug : 환경변수 email.verification.url를 읽지 못하는 문제 해결
  src/main/resources/application.yaml
Labels: 🐛bug

#23 Ref/group @Data 어노테이션 관련 리팩토링
  src/main/java/com/even/zaro/controller/GroupController.java
  src/main/java/com/even/zaro/dto/group/GroupCreateRequest.java
  src/main/java/com/even/zaro/dto/group/GroupEditRequest.java
  src/main/java/com/even/zaro/dto/group/GroupResponse.java
  src/main/java/com/even/zaro/entity/FavoriteGroup.java
  src/main/java/com/even/zaro/service/GroupService.java
Labels: ♻️refactored

#26 ref/favorite 즐겨찾기 API 리팩토링
  src/main/java/com/even/zaro/entity/Favorite.java
  src/main/java/com/even/zaro/entity/Place.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/FavoriteRepository.java
  src/main/java/com/even/zaro/service/FavoriteService.java
Labels: ♻️refactored

#27 Feat/password reset 비밀번호 재설정 메일 전송 및 비밀번호 재설정
  src/main/java/com/even/zaro/controller/AuthController.java
  src/main/java/com/even/zaro/dto/auth/PasswordResetEmailRequestDto.java
  src/main/java/com/even/zaro/dto/auth/PasswordResetEmailResponseDto.java
  src/main/java/com/even/zaro/dto/auth/PasswordResetRequestDto.java
  src/main/java/com/even/zaro/entity/PasswordResetToken.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/PasswordResetRepository.java
  src/main/java/com/even/zaro/service/AuthService.java
  src/main/java/com/even/zaro/service/EmailService.java
  src/main/java/com/even/zaro/service/EmailServiceImpl.java
  src/main/java/com/even/zaro/service/EmailVerifyService.java
Labels: ✨feature

#28 Bug : DTO에는 imageUrl -> thumbnailUrl로 명칭 변경되지 않은 에러 수정
  src/main/java/com/even/zaro/dto/profile/UserPostDto.java
Labels: 🐛bug

#29 Ref/profile : 기본정보조회 외의 profile api에 로그인 인증추가
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/ProfileController.java
Labels: ♻️refactored

#31 Ref/password-reset 이메일 전송 관련 코드 리팩토링
  build.gradle
  src/main/java/com/even/zaro/config/SchedulingConfig.java
  src/main/java/com/even/zaro/controller/AuthController.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/scheduler/TokenCleanupScheduler.java
  src/main/java/com/even/zaro/repository/EmailTokenRepository.java
  src/main/java/com/even/zaro/repository/PasswordResetRepository.java
  src/main/java/com/even/zaro/service/AuthService.java
  src/main/java/com/even/zaro/service/EmailService.java
  src/main/java/com/even/zaro/service/EmailServiceImpl.java
  src/main/java/com/even/zaro/service/EmailVerificationService.java
  src/main/java/com/even/zaro/service/PasswordResetService.java
  src/test/java/com/even/zaro/global/scheduler/TokenCleanupSchedulerTest.java
  src/test/resources/application-test.yml
Labels: ♻️refactored, ✅test

#35 hotfix: 비밀번호 재설정 메일 프론트 개발 주소 추가
  src/main/java/com/even/zaro/service/EmailService.java
Labels: 🐛bug

#36 Test/group 성공 테스트 케이스 작성
  src/main/java/com/even/zaro/dto/group/GroupCreateRequest.java
  src/main/java/com/even/zaro/dto/group/GroupEditRequest.java
  src/test/java/com/even/zaro/group/GroupAPITest.java
Labels: ✅test

#42 Feat/social login 카카오 로그인 API 구현
  src/main/java/com/even/zaro/controller/AuthController.java
  src/main/java/com/even/zaro/dto/auth/KakaoSignInRequestDto.java
  src/main/java/com/even/zaro/dto/auth/KakaoUserInfoDto.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/UserRepository.java
  src/main/java/com/even/zaro/service/AuthService.java
  src/main/java/com/even/zaro/service/KakaoOAuthService.java
Labels: 🐛bug, ✨feature

#40 Feat/notification : DB Listener로 알림 자동생성 로직, 인증된 사용자 알림목록조회 API 구현
  src/main/java/com/even/zaro/config/SpringContext.java
  src/main/java/com/even/zaro/controller/NotificationController.java
  src/main/java/com/even/zaro/dto/UserPostDto.java
  src/main/java/com/even/zaro/dto/notification/NotificationDto.java
  src/main/java/com/even/zaro/entity/Comment.java
  src/main/java/com/even/zaro/entity/Follow.java
  src/main/java/com/even/zaro/entity/Notification.java
  src/main/java/com/even/zaro/entity/PostLike.java
  src/main/java/com/even/zaro/listener/CommentListener.java
  src/main/java/com/even/zaro/listener/FollowListener.java
  src/main/java/com/even/zaro/listener/PostLikeListener.java
  src/main/java/com/even/zaro/repository/NotificationRepository.java
  src/main/java/com/even/zaro/service/NotificationService.java
Labels: ✨feature

#43 Test/favorite Favorite API 성공 테스트 케이스 추가
  src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
  src/main/java/com/even/zaro/dto/favorite/FavoriteEditRequest.java
  src/test/java/com/even/zaro/favorite/FavoriteApiTest.java
Labels: ✅test

#47 Fix/user nickname unique
  src/main/java/com/even/zaro/dto/auth/SignUpRequestDto.java
  src/main/java/com/even/zaro/entity/Comment.java
  src/main/java/com/even/zaro/entity/FavoriteGroup.java
  src/main/java/com/even/zaro/entity/Post.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/scheduler/TokenCleanupScheduler.java
  src/main/java/com/even/zaro/repository/UserRepository.java
  src/main/java/com/even/zaro/service/AuthService.java
  src/test/java/com/even/zaro/service/AuthServiceTest.java
Labels: 🐛bug

#45 Feat/post like 게시글 좋아요 API 구현
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/PostController.java
  src/main/java/com/even/zaro/dto/post/HomePostPreviewResponse.java
  src/main/java/com/even/zaro/dto/post/PostCreateRequest.java
  src/main/java/com/even/zaro/dto/post/PostDetailResponse.java
  src/main/java/com/even/zaro/dto/post/PostPreviewDto.java
  src/main/java/com/even/zaro/dto/post/PostUpdateRequest.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/PostLikeRepository.java
  src/main/java/com/even/zaro/service/PostLikeService.java
Labels: ✨feature

#50 Feat/comment c 기본 댓글 생성 API
  src/main/java/com/even/zaro/controller/CommentController.java
  src/main/java/com/even/zaro/dto/comment/CommentRequestDto.java
  src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
  src/main/java/com/even/zaro/entity/Comment.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/repository/CommentRepository.java
  src/main/java/com/even/zaro/service/CommentService.java
Labels: ✨feature

#49 Feat/notification : 알림 개별 읽기 api, 알림 전체읽기 api, 알림 자동삭제 스케줄링 구현
  src/main/java/com/even/zaro/controller/NotificationController.java
  src/main/java/com/even/zaro/entity/Notification.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/global/exception/notification/NotificationException.java
  src/main/java/com/even/zaro/global/scheduler/NotificationCleanupScheduler.java
  src/main/java/com/even/zaro/repository/NotificationRepository.java
  src/main/java/com/even/zaro/service/NotificationService.java
Labels: ✨feature

#55 Feat/comment r 댓글 리스트 조회 API 구현 및 공통 page response 추가
  src/main/java/com/even/zaro/controller/CommentController.java
  src/main/java/com/even/zaro/dto/PageResponse.java
  src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
  src/main/java/com/even/zaro/service/CommentService.java
Labels: ✨feature, ♻️refactored

#59 Fix/email detail 이메일 인증/비밀번호 재설정 메일 템플릿 적용
  src/main/java/com/even/zaro/service/EmailService.java
  src/main/resources/email/email-verification-template.html
  src/main/resources/email/password-reset-template.html
Labels: ✨feature

#56 Feat/by-cordinate-list 좌표기반 인근 장소 조회 API 구현
  src/main/java/com/even/zaro/config/QueryDslConfig.java
  src/main/java/com/even/zaro/controller/MapController.java
  src/main/java/com/even/zaro/dto/map/PlaceResponse.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/MapQueryRepository.java
  src/main/java/com/even/zaro/service/MapService.java
Labels: ✨feature

#61 Feat/search 검색 API 구현
  src/main/java/com/even/zaro/config/QueryDslConfig.java
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/PostController.java
  src/main/java/com/even/zaro/controller/PostSearchController.java
  src/main/java/com/even/zaro/dto/post/PostSearchDto.java
  src/main/java/com/even/zaro/entity/Post.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/PostSearchRepository.java
  src/main/java/com/even/zaro/repository/PostSearchRepositoryCustom.java
  src/main/java/com/even/zaro/repository/PostSearchRepositoryImpl.java
  src/main/java/com/even/zaro/service/PostSearchService.java
Labels: ✨feature

#66 QueryDslConfig 파일 복구
  src/main/java/com/even/zaro/config/QueryDslConfig.java
Labels: 🐛bug

#62 Test/map-exception 지도 API 예외 테스트 케이스 추가
  src/main/java/com/even/zaro/global/exception/map/MapException.java
  src/main/java/com/even/zaro/service/MapService.java
  src/test/java/com/even/zaro/map/MapApiTest.java
Labels: ✅test

#63 Feat/comment reply tag 답글 달기 기능 추가
  src/main/java/com/even/zaro/controller/CommentController.java
  src/main/java/com/even/zaro/dto/comment/CommentRequestDto.java
  src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
  src/main/java/com/even/zaro/dto/comment/MentionedUserDto.java
  src/main/java/com/even/zaro/entity/Comment.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/UserRepository.java
  src/main/java/com/even/zaro/service/CommentService.java
Labels: ✨feature

#72 Ref/post 공통 Page 리팩토링 및 버그 수정
  src/main/java/com/even/zaro/controller/PostController.java
  src/main/java/com/even/zaro/controller/PostSearchController.java
  src/main/java/com/even/zaro/service/PostSearchService.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: 🐛bug, ♻️refactored

#76 ref: URL -> Image 변경 PostService 누락
  src/main/java/com/even/zaro/service/PostService.java
Labels: ♻️refactored

#78 Hotfix/image url db 에러 해결
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: 🐛bug

#82 Test/notification : 알림 기능 성공/예외 통합 테스트코드 구현
  src/main/java/com/even/zaro/entity/Notification.java
  src/main/java/com/even/zaro/global/exception/notification/NotificationException.java
  src/main/java/com/even/zaro/global/scheduler/NotificationCleanupScheduler.java
  src/test/java/com/even/zaro/global/scheduler/NotificationCleanupSchedulerTest.java
  src/test/java/com/even/zaro/notification/notificationApiTest.java
Labels: ✅test

#83 Feat/postReport : 게시글 신고 API 구현
  src/main/java/com/even/zaro/controller/PostController.java
  src/main/java/com/even/zaro/dto/post/ReportRequestDTO.java
  src/main/java/com/even/zaro/dto/post/ReportResponseDto.java
  src/main/java/com/even/zaro/entity/Post.java
  src/main/java/com/even/zaro/entity/PostReport.java
  src/main/java/com/even/zaro/entity/ReportReasonType.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/repository/PostReportRepository.java
  src/main/java/com/even/zaro/repository/PostRepository.java
  src/main/java/com/even/zaro/service/PostReportService.java
  src/main/java/com/even/zaro/service/PostService.java
Labels: ✨feature

#86 Feat/search es Elasticsearch 적용 검색 API 구현
  .env.dev.example
  .env.local.example
  .env.prod.example
  build.gradle
  docker-compose.dev.yml
  docker-compose.prod.yml
  src/main/java/com/even/zaro/config/ElasticsearchConfig.java
  src/main/java/com/even/zaro/config/security/SecurityConfig.java
  src/main/java/com/even/zaro/controller/PostSearchController.java
  src/main/java/com/even/zaro/elasticsearch/ReindexController.java
  src/main/java/com/even/zaro/elasticsearch/document/PostEsDocument.java
  src/main/java/com/even/zaro/event/PostDeletedEvent.java
  src/main/java/com/even/zaro/event/PostSavedEvent.java
  src/main/java/com/even/zaro/global/ErrorCode.java
  src/main/java/com/even/zaro/listener/PostDeletedEventListener.java
  src/main/java/com/even/zaro/listener/PostSavedEventListener.java
  src/main/java/com/even/zaro/service/PostEsSearchService.java
  src/main/java/com/even/zaro/service/PostSearchService.java
  src/main/java/com/even/zaro/service/PostService.java
  src/main/resources/application.yaml
Labels: ✨feature

#87 ref: 리스트조회 content 자르는거 수정
  src/main/java/com/even/zaro/dto/post/PostPreviewDto.java
Labels: ♻️refactored

#89 fix: es 저장시 content 이미지 url, html, 여러 줄바꿈 생략
  src/main/java/com/even/zaro/elasticsearch/document/PostEsDocument.java
Labels: 🐛bug

#91 Ref/page response : 프로필 기능 내 공통 Page 응답 dto 리팩토링
  src/main/java/com/even/zaro/controller/ProfileController.java
  src/main/java/com/even/zaro/service/ProfileService.java
Labels: ♻️refactored

#96 Fix/docker again 도커파일 재수정 및 도커 ignore 추가
  .dockerignore
  Dockerfile
Labels: 🐛bug

#100 fix/profile-test : 변경된 getUserPosts메서드 리턴타입에 맞게 testCode 수정
  src/test/java/com/even/zaro/profile/ProfileApiTest.java
Labels: 🐛bug

#101 Feat/update profile 프로필(계정정보) 변경 API
  src/main/java/com/even/zaro/controller/UserController.java
  src/main/java/com/even/zaro/dto/profile/UserProfileDto.java
  src/main/java/com/even/zaro/dto/user/UpdateProfileRequestDto.java
  src/main/java/com/even/zaro/dto/user/UpdateProfileResponseDto.java
  src/main/java/com/even/zaro/dto/user/UserInfoResponseDto.java
  src/main/java/com/even/zaro/entity/Gender.java
  src/main/java/com/even/zaro/entity/Mbti.java
  src/main/java/com/even/zaro/entity/User.java
  src/main/java/com/even/zaro/service/AuthService.java
  src/main/java/com/even/zaro/service/UserService.java
  src/test/java/com/even/zaro/service/UserServiceTest.java
Labels: ✨feature
